name = "memory-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "memory-mcp"
database_id = "e35a1410-1485-49b6-8e2c-262e32a34ba1"

[[vectorize]]
binding = "VECTORIZE"
index_name = "memory-vectors"
